// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:system_mapper/data/hive_objects/front/front.dart';
import 'package:system_mapper/data/hive_objects/front/front_entry.dart';
import 'package:system_mapper/data/hive_objects/member.dart';
import 'package:system_mapper/data/hive_objects/system.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(FrontAdapter());
    registerAdapter(FrontEntryAdapter());
    registerAdapter(MemberAdapter());
    registerAdapter(SystemAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(FrontAdapter());
    registerAdapter(FrontEntryAdapter());
    registerAdapter(MemberAdapter());
    registerAdapter(SystemAdapter());
  }
}
